### ISSUE TITLE
API Token in Public Repository

### ISSUE THREAD

**Issue by ChristopherHammond13** [leejys/uclapi_slackroombot#1]
https://github.com/leejys/uclapi_slackroombot/blob/ac0cf3021ee69b6cf6aa90813aaa594ee26c827d/roombot.py#L20

Hey! 👋  Just a quick heads up that you published an API token in a public repo. Please refrain from doing this by using a settings file that is not committed (then documenting this in an example settings file). After, use the API Dashboard to refresh your token to something new :)

`.env` is a nice standard way of doing this https://github.com/theskumar/python-dotenv

**Comment by leejys** [comment]
Hey Chris, thanks for letting me know! I will fix this and regenerate those shortly...

**Comment by leejys** [comment]
Have fixed this, regenerated tokens and cleaned up the repo history. Thanks for the link, that was really helpful :)
